from enum import Enum
from typing import Annotated, Literal

from pydantic import BaseModel, Field, model_validator

from app.schemas.idea import IdeaPriority, IdeaStatus


class ProposalType(str, Enum):
	idea_update = "idea_update"
	idea_creation = "idea_creation"
	task_creation = "task_creation"


class ProposalStatus(str, Enum):
	pending = "pending"    # waiting for user decision
	accepted = "accepted"  # user clicked Accept
	rejected = "rejected"  # user clicked Reject


class IdeaUpdateProposal(BaseModel):
	proposal_type: Literal[ProposalType.idea_update] = ProposalType.idea_update
	proposal_id: str = Field(..., min_length=1)  # UUID generated by server
	status: ProposalStatus = ProposalStatus.pending
	idea_id: str = Field(..., min_length=1)  # MongoDB _id of the idea
	current_title: str = Field(..., min_length=1, max_length=200)
	new_title: str = Field(..., min_length=1, max_length=200)
	current_description: str | None = Field(default=None, max_length=50000)
	new_description: str | None = Field(default=None, max_length=50000)
	new_status: IdeaStatus | None = None
	new_priority: IdeaPriority | None = None
	reasoning: str = Field(..., min_length=1)


class IdeaCreationProposal(BaseModel):
	proposal_type: Literal[ProposalType.idea_creation] = ProposalType.idea_creation
	proposal_id: str = Field(..., min_length=1)
	status: ProposalStatus = ProposalStatus.pending
	title: str = Field(..., min_length=1, max_length=200)
	description: str = Field(..., min_length=1, max_length=50000)
	proposed_status: IdeaStatus = IdeaStatus.raw
	proposed_priority: IdeaPriority = IdeaPriority.low
	tags: list[str] = Field(default_factory=list)
	reasoning: str = Field(..., min_length=1)


class TaskCreationProposal(BaseModel):
	proposal_type: Literal[ProposalType.task_creation] = ProposalType.task_creation
	proposal_id: str = Field(..., min_length=1)
	status: ProposalStatus = ProposalStatus.pending
	idea_id: str = Field(..., min_length=1)
	idea_title: str = Field(..., min_length=1, max_length=200)
	task_title: str = Field(..., min_length=1, max_length=200)
	task_description: str | None = Field(default=None, max_length=600)
	reasoning: str = Field(..., min_length=1)


# Discriminated union for robust proposal parsing/validation.
Proposal = Annotated[
	IdeaUpdateProposal | IdeaCreationProposal | TaskCreationProposal,
	Field(discriminator="proposal_type"),
]


class AgentResponse(BaseModel):
	"""
	Full response from the agent for one user message.
	Contains assistant text and optional proposals awaiting approval.
	"""

	message: str = Field(..., min_length=1)
	proposals: list[Proposal] = Field(default_factory=list)


class ProposalDecision(BaseModel):
	"""
	Frontend payload when a user accepts or rejects a proposal.
	
	For accept, the full proposal payload is required so backend can execute it.
	For reject, proposal payload is optional.
	"""

	proposal_id: str = Field(..., min_length=1)
	decision: Literal["accept", "reject"]
	proposal: Proposal | None = None

	@model_validator(mode="after")
	def validate_accept_has_proposal(self):
		if self.decision == "accept" and self.proposal is None:
			raise ValueError("proposal is required when decision is 'accept'")
		if self.proposal is not None and self.proposal.proposal_id != self.proposal_id:
			raise ValueError("proposal_id must match proposal.proposal_id")
		return self
