from enum import Enum
from typing import Annotated, Literal

from pydantic import BaseModel, Field, model_validator

from app.schemas.idea import IdeaPriority, IdeaStatus


class ProposalType(str, Enum):
	# This enum is the discriminator used to decide which concrete proposal
	# schema should parse a payload coming back from the agent/frontend.
	idea_update = "idea_update"
	idea_creation = "idea_creation"
	task_creation = "task_creation"


class ProposalStatus(str, Enum):
	# Pending = proposed but not executed yet.
	# Accepted/rejected describe the user decision in the approval workflow.
	pending = "pending"    # waiting for user decision
	accepted = "accepted"  # user clicked Accept
	rejected = "rejected"  # user clicked Reject


class IdeaUpdateProposal(BaseModel):
	# Update proposals show a before/after style contract so the user can review
	# what will change before the backend writes anything.
	proposal_type: Literal[ProposalType.idea_update] = ProposalType.idea_update
	proposal_id: str = Field(..., min_length=1)  # UUID generated by server
	status: ProposalStatus = ProposalStatus.pending
	idea_id: str = Field(..., min_length=1)  # MongoDB _id of the idea
	current_title: str = Field(..., min_length=1, max_length=200)
	new_title: str = Field(..., min_length=1, max_length=200)
	current_description: str | None = Field(default=None, max_length=50000)
	new_description: str | None = Field(default=None, max_length=50000)
	# Summary feeds the embedding/vector index, so the agent only proposes a new
	# summary when a title/description change genuinely shifts the idea's meaning.
	# Both are optional: a minor edit (typo/wording) leaves the summary untouched.
	current_summary: str | None = Field(default=None, max_length=2000)
	new_summary: str | None = Field(default=None, max_length=2000)
	new_status: IdeaStatus | None = None
	new_priority: IdeaPriority | None = None
	reasoning: str = Field(..., min_length=1)


class IdeaCreationProposal(BaseModel):
	# Creation proposals contain the exact document content the agent wants the
	# backend to create after the user approves it.
	proposal_type: Literal[ProposalType.idea_creation] = ProposalType.idea_creation
	proposal_id: str = Field(..., min_length=1)
	status: ProposalStatus = ProposalStatus.pending
	title: str = Field(..., min_length=1, max_length=200)
	description: str = Field(..., min_length=1, max_length=50000)
	proposed_status: IdeaStatus = IdeaStatus.raw
	proposed_priority: IdeaPriority = IdeaPriority.low
	tags: list[str] = Field(default_factory=list)
	reasoning: str = Field(..., min_length=1)


class TaskCreationProposal(BaseModel):
	# Task proposals target an existing parent idea, so they carry both the
	# parent idea id (for execution) and title (for display/review).
	proposal_type: Literal[ProposalType.task_creation] = ProposalType.task_creation
	proposal_id: str = Field(..., min_length=1)
	status: ProposalStatus = ProposalStatus.pending
	idea_id: str = Field(..., min_length=1)
	idea_title: str = Field(..., min_length=1, max_length=200)
	task_title: str = Field(..., min_length=1, max_length=200)
	task_description: str | None = Field(default=None, max_length=600)
	reasoning: str = Field(..., min_length=1)


# Discriminated union for robust proposal parsing/validation.
# Pydantic reads proposal_type first, then routes the payload into the correct
# proposal model. This is why an empty object {} cannot be parsed as Proposal.
Proposal = Annotated[
	IdeaUpdateProposal | IdeaCreationProposal | TaskCreationProposal,
	Field(discriminator="proposal_type"),
]


class AgentResponse(BaseModel):
	"""
	Full response from the agent for one user message.
	Contains assistant text and optional proposals awaiting approval.
	"""

	message: str = Field(..., min_length=1)
	proposals: list[Proposal] = Field(default_factory=list)


class ProposalDecision(BaseModel):
	"""
	Frontend payload when a user accepts or rejects a proposal.
	
	For accept, the full proposal payload is required so backend can execute it.
	For reject, proposal payload is optional.
	"""

	proposal_id: str = Field(..., min_length=1)
	decision: Literal["accept", "reject"]
	# Accept path needs the actual proposal body because the backend executes
	# that payload. Reject path can omit it because no write occurs.
	proposal: Proposal | None = None

	@model_validator(mode="after")
	def validate_accept_has_proposal(self):
		# Validation happens after parsing so we can enforce workflow rules:
		# - accept must include a proposal
		# - top-level proposal_id must match the nested proposal payload
		if self.decision == "accept" and self.proposal is None:
			raise ValueError("proposal is required when decision is 'accept'")
		if self.proposal is not None and self.proposal.proposal_id != self.proposal_id:
			raise ValueError("proposal_id must match proposal.proposal_id")
		return self
